# Generated by Django 3.1 on 2020-09-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20200904_2240'),
        ('accounts', '0002_auto_20200904_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='productivity.department'),
        ),
    ]
