# Generated by Django 3.1 on 2020-09-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_auto_20200905_0010'),
        ('accounts', '0004_auto_20200904_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productivity.department'),
        ),
    ]
