# Generated by Django 3.1 on 2020-09-04 21:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20200904_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='productivity.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
