# Generated by Django 3.1 on 2020-09-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20200904_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='description',
            field=models.CharField(blank=True, help_text='Optional. Description of the task (Eg. Used for when case handlers log PPI cases, etc.', max_length=250, null=True),
        ),
    ]
